# 服务端口号
server:
  port: 8000
#eureka 基本信息配置
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      #注册到eureka的服务地址
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/,http://${eureka.instance.hostname}:9100/eureka/,http://${eureka.instance.hostname}:7100/eureka/
    #需要将我的服务注册到eureka上
    register-with-eureka: true
    #需要检索服务
    fetch-registry: true
spring:
  application:
    name: kk-story-server
