server:
  port: 8888
# 暂时关闭eureka注册发现
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false

spring:
  #数据库连接信息
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/kzone?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
    username: root
    password: 1234
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
